### PR TITLE
Optimized RC oscillator calibration

### PR DESCRIPTION
**Pull request by cpldcpu**
In the meantime I rewrote the entire oscillator calibration in assembler, saving 90 bytes in total. All changes reside in "libs-device" now, the usb-driver does not have to be altered.

osccal.c and usbMeasureFrameLength are not needed anymore. All functionality has been implemented in osccalASM.S with minor changes to osccal.h for the hook.
## Original pull request:

I spent some time optimizing calibrateOscillator(void). The new implementation has been debugged on an ATtiny 85 and was confirmed to converge to the same osccal value as the previous implementation. If desired, I can also supply some debug data. I used a SPI connection to monitor the new implementation in real time.
## Benefits:
-    Codesize reduced by 90 bytes.
-    Improved robustness due to removing timeout from frame length measurement and inserted NOP after OSCCAL writes.
## Changes:
-    The new routine performs a combined binary and neighborhood search in a single loop. Note that the neighborhood search is necessary due to the quasi-monotonic nature of OSCCAL. (See Atmel application note AVR054).
-   Inserted NOP after writes to OSCCAL to avoid CPU errors during oscillator stabilization.
-   Implemented new routine to measure frame time "usbMeasureFrameLengthDecreasing". This routine takes the target time as a parameter and returns the deviation.This routine is now part of the assembler code.
-  usbMeasureFrameLengthDecreasing measures in multiples of 5 cycles and is thus slighly more accurate.
-  usbMeasureFrameLengthDecreasing does not support time out anymore. The original implementation returned zero in case of time out, which would have caused the old calibrateOscillator() implementation to increase OSSCAL to 255, effictively overclocking and most likely crashing the CPU. The new implementation will enter an infinite loop when no USB activity is encountered. The user program should use the watchdog to escape from situations like this.

### CODE REVIEW

**Comment by NicoHood** [comment]
Is this project abandonned or does someone still work on this? Cant they move the ownership to someone who care for it?

**Comment by starkjohann** [comment]
Sorry for not responding for a long time -- I don't use github regularly, so I don't check the messages here. A note on our support channel would be great!

Regarding the PR: I prefer to provide the C implementation in the examples because it's easier to understand and customize, but I would like to include a link to your improved version for people who just want something which works efficiently. Unfortunately the github link is broken. Have you moved the project?

**Comment by cpldcpu** [comment]
You can find the entire project here, including the optimized osccal.

https://github.com/micronucleus/micronucleus/tree/master/firmware

Might be of interest to you - it uses a significantly modified version of V-USB now, which does not need interrupts.

**Comment by starkjohann** [comment]
Hi Tim,
> On 24 Jan 2017, at 22:45, Tim <notifications@github.com> wrote:
> 
> You can find the entire project here, including the optimized osccal.
> 
> https://github.com/micronucleus/micronucleus/tree/master/firmware
> 
> Might be of interest to you - it uses a significantly modified version of V-USB now, which does not need interrupts.

Thanks!

I’ve read about micronucleous and wanted to check it out later(tm), but I have almost no remaining free time since 2013 where my second daughter was born...

Regards, Christian.

-- 
DI Christian Starkjohann <cs@obdev.at>
OBJECTIVE DEVELOPMENT Software GmbH

**Comment by cpldcpu** [comment]
Well, no worries. There haven't been a lot of changes to Micronucleus lately, so it will still be the same later. I see the issue with lack of time...

You may also be interested in this, which also started out with V-USB:

https://github.com/cpldcpu/u-wire

Best Regards,
Tim

**Pull request closed without merging**
